name: Continuous Integration

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Compile
        run: go build main.go
      - name: Vet
        run: go vet -v ./...
